In [1]:
# Import relevant modules
import numpy as np
import time
import import_ipynb

In [2]:
# Import the functions file we created with the functions to solve the Sudoku
import functions

importing Jupyter notebook from functions.ipynb


In [3]:
# The Sudoku grid is requested and stored in a variable
# You can use the following grid (normal-hard sudoku):
# 000090010300010200000400067007500000006029081509000000200000000008000000160305002
# Or the hardest Sudoku in the world:
# 800000000003600000070090200050007000000045700000100030001000068008500010090000400
user_input = input(
    'Enter your sudoku.\
                    Type the numbers, separated with commas, from the grid row by row, from left to right. \
                    Use zero (0) for empty cells.  \
                    Tap "quit" to quit.'
)

# User input is converted into integers and put in a list
user_input = [int(i) for i in user_input]

# We transform user input into a 2-dimensional Numpy array
grid = functions.make_grid(user_input)

print(grid)

Enter your sudoku.                    Type the numbers, separated with commas, from the grid row by row, from left to right.                     Use zero (0) for empty cells.                      Tap "quit" to quit. 000090010300010200000400067007500000006029081509000000200000000008000000160305002


[[0 0 0 0 9 0 0 1 0]
 [3 0 0 0 1 0 2 0 0]
 [0 0 0 4 0 0 0 6 7]
 [0 0 7 5 0 0 0 0 0]
 [0 0 6 0 2 9 0 8 1]
 [5 0 9 0 0 0 0 0 0]
 [2 0 0 0 0 0 0 0 0]
 [0 0 8 0 0 0 0 0 0]
 [1 6 0 3 0 5 0 0 2]]


In [4]:
# We now use the function we created to solve the Sudoku and we time it
%time functions.solve_sudoku(grid)

CPU times: user 1.02 s, sys: 31.2 ms, total: 1.05 s
Wall time: 1.15 s


array([[6, 7, 2, 8, 9, 3, 4, 1, 5],
       [3, 4, 5, 6, 1, 7, 2, 9, 8],
       [9, 8, 1, 4, 5, 2, 3, 6, 7],
       [8, 1, 7, 5, 3, 4, 6, 2, 9],
       [4, 3, 6, 7, 2, 9, 5, 8, 1],
       [5, 2, 9, 1, 6, 8, 7, 3, 4],
       [2, 5, 3, 9, 7, 1, 8, 4, 6],
       [7, 9, 8, 2, 4, 6, 1, 5, 3],
       [1, 6, 4, 3, 8, 5, 9, 7, 2]])